fuergaosi233/wechat-chatgpt

.github/workflows/publish-docker-hub.yml

💚 Change CI file name

---

README.md
config.yaml.example
src/chatgpt.ts
src/config.ts

Sometimes, too many useless messages can also trigger API abuse, so it is important to add a keyword to control whether to reply. Note that the keyword should appear in the first position.
Next, I am thinking about how to automatically update the token problem, the token will expire in about 2 hours.

add trigger keywords in a configuration

---

package.json
src/chatgpt.ts

fix: no keywords forEach error

---

README.md

Updated readme with the correct docker image

---

Dockerfile

[fix][bug] No module named 'revChatGPT'

---

poetry.lock
pyproject.toml

- Upgrade revchatGPT to resolve:
- https://github.com/fuergaosi233/wechat-chatgpt/issues/104

⬆️ Upgrade revChatGPT version

---

pyproject.toml

leaving the latest version works

fixing dependencies cause docker build failure

---

README.md
README_ZH.md

How to Update Docker Image

---

README.md
README_ZH.md

🎉 Anyone can deploy their Bot via Railway now.

📝 Add Railway deploy

---

README.md
README_ZH.md

Add more explanation in upgrade docker version wiki

---

README_ZH.md

Fix some details in translation

Update Chinese translation

---

config.yaml.example
src/chatgpt.ts
src/config.ts
src/generate_session.py
src/interface.ts

You can configure a separate Proxy for OpenAI login!

✨ Add OpenAi Proxy config

---

src/chatgpt.ts

#171 
同一个人在不同群里独立的conversation，避免上下文泄漏，减少429问题

feat: everyone in every room  have their own session

---

config.yaml.example
src/chatgpt.ts
src/config.ts
src/interface.ts

Add blocking words detection function

feat: 🎸 Add blocking words detection function

---

config.yaml.example
package-lock.json
package.json
src/chatgpt.ts
src/config.ts
src/interface.ts

- Add cf_clearance token support for antibot

✨ Add cf_clearance token support

---

package-lock.json
package.json

bumping the chartGPT to [2.2.0](https://www.npmjs.com/package/chatgpt?activeTab=versions).

chore: update chatgpt to 2.2.0

---

README_ZH.md

docs: ✏️ fix chinese documents

---

config.yaml.example
src/chatgpt.ts
src/interface.ts

Support google login

---

README.md
README_ZH.md

docs: ✏️ add docker and railway error note

docs: ✏️ add docker and railway error note

---

README_ZH.md

docs: ✏️ update README_ZH

---

README.md
README_ZH.md

Add dependency version information
✅ Closes: #441

docs: ✏️ Add dependency version information

---

package-lock.json
package.json

https://github.com/fuergaosi233/wechat-chatgpt/issues/484

⬆️ Upgrade chatgpt

---

.env.example
README.md
README_ZH.md
docker-compose.yml

docs: ✏️ modify readme

---

package.json
src/bot.ts
src/chatgpt.ts
src/main.ts

fix: 🐛 修复bot不回复的bug

---

README.md
README_ZH.md

fix: 🐛 fix typo

---

README.md
README_ZH.md

feat: 🎸 Add railway deploy

---

.dockerignore
README.md
README_ZH.md

docs: ✏️ Add Fly.io deployment

---

package-lock.json
package.json
src/main.ts

fix: 🐛 Fix docker start error

---

Dockerfile
src/main.ts

Fix the bug that docker failed to start

fix: 🐛 Fix the bug that docker failed to start

---

.gitignore
src/bot.ts
src/main.ts
src/openai.ts

feat: 🎸 Add whisper support

---

README.md
README_ZH.md
config.yaml.example
src/chatgpt.ts
src/config.ts
src/interface.ts

fix: 'tigger' to 'trigger'

---

.github/ISSUE_TEMPLATE/bug_report.yml
README.md

Add issues template

---

package-lock.json
package.json
src/bot.ts
src/data.ts
src/openai.ts
src/utils.ts

- Add GPT3Tokenizer library for tokenization
- Add a default response when GPT response is empty
- Add a check for blocked words in GPT response
- Change temperature parameter to `0.6`
- Add error handling for OpenAI API request
- Return OpenAI response as a string
- Add check for token limit before adding a user or assistant message
- Delete messages when token limit is exceeded
[src/utils.ts]
- Add the GPT3Tokenizer library for tokenization
- Add a function to calculate the number of tokens in a chat message
- Add a function to check if the number of tokens exceeds the limit for the current model [src/bot.ts]
- Add a default response when the GPT response is empty
- Add a check for blocked words in the GPT response [src/openai.ts]
- Change the temperature parameter to `0.6`
- Add error …

Fix api error caused when the token exceeds the limit

---

src/bot.ts
src/utils.ts

Fix the problem that special symbols are set as trigger. [issue](https://github.com/fuergaosi233/wechat-chatgpt/issues/799)

fix invalid regular expression and typo

---

.github/ISSUE_TEMPLATE/config.yml

docs: ✏️ Add discord link
